### ISSUE TITLE
Empty Project View

### ISSUE THREAD

**Issue by lbeckman314** [ACED-IDP/compose-services-training#12]
# Error

The [Project View](https://aced-training.compbio.ohsu.edu/MyFirstProgram-MyFirstProject) does not show the expected node graph.

<img width="90%" alt="Screen Shot 2022-10-18 at 4 31 01 PM" src="https://user-images.githubusercontent.com/15309567/196564002-dac1bfbc-4205-41e2-a047-b32f2a920814.png">

# Reproduce

1) Run docker-compose to verify all services are up (`dc up -d`).
2) Visit the [Project View](https://aced-training.compbio.ohsu.edu/MyFirstProgram-MyFirstProject) in the browser.

# Possible fix

The name of the tables in PostgreSQL being created include capital letters (e.g. node_Condition) which require quotation marks when running queries:
- `SELECT count(*) FROM "node_Condition";` returns 4311
- `SELECT count(*) FROM node_Condition;` returns ERROR:  relation "node_condition" does not exist

The queries being run in peregrine-service  on metadata upload do not include the necessary quotes around the table names as far as I can tell, resulting in the relation does not exist error.
Example: `SQL: SELECT (SELECT count(*) FROM node_Condition WHERE...`

Match the new data model schema names with lowercase labels somewhere in the data schema or config file. I will see what the default Gen3 data schema does as far as case sensitivity goes.

**Comment by bwalsh** [comment]
I believe this is resolved now.  The new data model has all lower case table names.   Let's verify and close this issue  when you deploy locally.
